### ISSUE TITLE
problem when instantiate datamodule in test.py file

### ISSUE THREAD

**Issue by XuekaiChen** [Babelscape/ner4el#2]

**Comment by sted97** [comment]
Hi @XuekaiChen, thanks for your interest!

I see that you deleted the description of the issue. Do you still have problems??

Best,
Simone Tedeschi

**Comment by XuekaiChen** [comment]
thanks for your reply!
I have already solved the deleted question.
but I still ran into some problems while reproduce the program.
it said
```
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []
```
but I can't find the right place to set the `self.device` variable. Does this mean the NVIDIA GPU must be configured? Or there are ways to get the CPU to run? 

really appreciate.

**Comment by sted97** [comment]
You can change the device to CPU by setting the **pl_trainer/gpus** parameter to 0 [here](https://github.com/Babelscape/ner4el/blob/master/ner4el/conf/train/default.yaml#L9).

In this case, you also need to change [this line](https://github.com/Babelscape/ner4el/blob/master/ner4el/src/pl_modules/model.py#L24) by replacing .cuda() with .cpu().

Hope this helps :)

**note**: the program is extremely slow on CPU (i.e. it could require hours only for testing) due to the large amount of computations

**Comment by XuekaiChen** [comment]
problem solved, thank you very much!!!
