### ISSUE TITLE
problems after the program runs

### ISSUE THREAD

**Issue by XuekaiChen** [Babelscape/ner4el#3]
Hi Mr. Tedeschi, it's me again. Sorry to bother you.
I followed the instructions in the README file to complete the testing section, but I can't find where to analyze the bad case. Is there a way to check it? 

Best,
Xuekai, Chen

**Comment by sted97** [comment]
Hi @XuekaiChen :)

What do you mean with "analyze the bad case"?

Did you obtain the results and you want to analyze where the system makes errors? Or do you mean something else?

Best,
Simone Tedeschi

**Comment by XuekaiChen** [comment]
Yes, I got the overall test accuracy, but I'd like to further analyze the specific classification of each sample.
I am sorry that my English expression is poor.

**Comment by sted97** [comment]
Don't worry, now it's perfectly clear! :)

What you can do to see the predictions is to add the following lines of code [here](https://github.com/Babelscape/ner4el/blob/master/ner4el/src/pl_modules/model.py#L152) (inside the for loop, at the same level of `all_labels.append(int(labels[i]))`) and also [here](https://github.com/Babelscape/ner4el/blob/master/ner4el/src/pl_modules/model.py#L215):
```
entry = {}
entry["prediction"] = list(zip(candidates[i].tolist(), normalized_similarities_line.tolist()))

with open(str(PROJECT_ROOT / "predictions.jsonl"), "a") as f:
    json.dump(entry, f)
    f.write("\n")
```
This fragment of code will write the predictions in the `predictions.jsonl` file in the following format:
`{"prediction": [[664791, 0.0], [9876015, 0.07438267767429352], [10966652, 0.5145593285560608], [49528, 0.0], [1729109, 0.04334160313010216], [10696656, 0.6969443559646606], [14470223, 0.1742844581604004], [17387730, 0.0], [230023, 0.8618601560592651], [10115171, 0.39411282539367676], [9303722, 0.29382163286209106], [19092261, 0.3113846480846405], [9514354, 0.5312284827232361], [18461611, 0.2923046350479126], [6016968, 0.0]]}`

You will have a prediction for each entry in the test set, and the prediction is a list of lists, where each list is made of 2 elements: the first is the candidate, and the second is its score. The candidate with the highest score is the prediction of the system.

Note that the test set is not shuffled, so the first prediction corresponds to the first entry in the dataset, the second prediction to the second entry, and so on. Also, note that if you want to replace the candidates' IDs with their corresponding Wikipedia titles (so that you can more easily check predictions), you can simply use the Title Dictionary (title_dict.pickle).

Hope this helps

**Comment by XuekaiChen** [comment]
Ok!  I'll try it right away!  Thank you for your detailed explanation, which was very helpful to me!! :) 👍 💯
